select * from Customer_Shipping_Behavior.dbo.customer

--Q1. What is the total revenue generated by male vs. female customers? 
select gender, SUM(purchase_amount) as Total_Revenue
from Customer_Shipping_Behavior.dbo.customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from Customer_Shipping_Behavior.dbo.customer
where discount_applied = 'yes' and purchase_amount > (select AVG(purchase_amount) from Customer_Shipping_Behavior.dbo.customer)

--Q3. Which are the top 5 products with the highest average review rating?
 select top 5 item_purchased, round(AVG(review_rating),2) as Average_Rating
 from Customer_Shipping_Behavior.dbo.customer
 group by item_purchased
 order by Average_Rating DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, AVG(purchase_amount) as Average_Purchase_Amount
from Customer_Shipping_Behavior.dbo.customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status, 
    COUNT(*) AS Number_of_Customers,  -- This will reveal why the revenue is higher!
    AVG(purchase_amount) AS Average_Spend, 
    SUM(purchase_amount) AS Total_Revenue
FROM Customer_Shipping_Behavior.dbo.customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
select top 5 item_purchased, 
       round((SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 2) as Discount_Percentage
       from Customer_Shipping_Behavior.dbo.customer
       group by item_purchased

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select 
    case 
        when previous_purchases = 0 then 'New' 
        when previous_purchases between 1 and 5 then 'Returning' 
        else 'Loyal' 
    end as Customer_Segment, 
    COUNT(*) as Number_of_Customers
    from Customer_Shipping_Behavior.dbo.customer
    where previous_purchases is not null
    group by case 
        when previous_purchases = 0 then 'New' 
        when previous_purchases between 1 and 5 then 'Returning' 
        else 'Loyal' 
    end
--Q8. What are the top 3 most purchased products within each category?
-- 1. We start by creating a "Common Table Expression" (CTE) called 'Ranked_Products'.
-- Think of a CTE as a temporary, invisible table we build in the background 
-- so that we can easily query and filter its results in the next step.
WITH Ranked_Products AS (
    SELECT 
        category, 
        item_purchased, 
        
        -- This calculates the total number of times this specific item was bought.
        COUNT(*) AS Purchase_Count,
        
        -- ----------------------------------------------------------------------
        -- This next line is the "Window Function" that solves the problem.
        -- It acts as a dynamic ranking system for our rows:
        -- 
        -- PARTITION BY category: This tells SQL to group the rankings by category. 
        -- It hits the "reset" button on the rank counter every time the category changes.
        --
        -- ORDER BY COUNT(*) DESC: This dictates how the rank is awarded. Highest count gets #1.
        -- ----------------------------------------------------------------------
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as Rank_In_Category
        
    FROM Customer_Shipping_Behavior.dbo.customer
    
    -- We must group by these two columns so the COUNT(*) function knows 
    -- exactly what it is supposed to be counting.
    GROUP BY category, item_purchased
)

-- 2. Now that our temporary 'Ranked_Products' table exists in memory (complete with rankings), 
-- we write a standard SELECT statement to grab the data from it.
SELECT 
    category, 
    item_purchased, 
    Purchase_Count
FROM Ranked_Products

-- 3. The magic step: We filter the results using the new 'Rank_In_Category' column we created.
-- We only want to keep rows where the item ranked 1st, 2nd, or 3rd in its category.
-- Everything ranked 4th or lower is ignored!
WHERE Rank_In_Category <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
COUNT(customer_id) as repeat_buyers
from Customer_Shipping_Behavior.dbo.customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as Total_Revenue
from Customer_Shipping_Behavior.dbo.customer
group by age_group
order by Total_Revenue DESC